sudo: required
services:
  - docker

before_install:
  - docker build -t xlreon/react-test -f ./client/Dockerfile ./client

script:
  - docker run xlreon/react-test npm test -- --coverage

after_success:
  - docker build -t xlreon/docker-client ./client
  - docker build -t xlreon/docker-nginx ./nginx
  - docker build -t xlreon/docker-server ./server
  - docker build -t xlreon/docker-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push xlreon/docker-client 
  - docker push xlreon/docker-nginx
  - docker push xlreon/docker-server
  - docker push xlreon/docker-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: docker-complex
    env: DockerComplex-env
    bucket_name: elasticbeanstalk-us-east-2-952941133223
    bucket_path: docker-complex
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: $AWS_SECRET_KEY
